# Generated by Django 2.0.1 on 2018-04-03 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maio.models.maiofields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('media_class', models.CharField(choices=[('images', 'Images'), ('video', 'Video'), ('audio', 'Audio'), ('documents', 'Documents'), ('other', 'Other')], max_length=32)),
                ('name', models.CharField(max_length=1024)),
                ('extension', models.CharField(blank=True, max_length=32, null=True)),
                ('mime_type', models.CharField(max_length=64)),
                ('num_bytes', models.PositiveIntegerField(default=0)),
                ('mtime', models.FloatField()),
                ('md5sum', maio.models.maiofields.FixedCharField(max_length=32, unique=True)),
                ('tn_path', models.CharField(max_length=1024)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_path_md5sum', maio.models.maiofields.FixedCharField(max_length=32, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-mtime'],
            },
        ),
        migrations.CreateModel(
            name='FileCaption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=1024)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('caption_date', models.DateTimeField(blank=True, null=True)),
                ('caption', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.File')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('extension', models.CharField(blank=True, max_length=32, null=True)),
                ('mtime', models.FloatField(default=0.0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('loves', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('author', models.CharField(blank=True, max_length=1024, null=True)),
                ('source', models.CharField(blank=True, max_length=1024, null=True)),
                ('copyright', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.File')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mtime'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('default_order', models.PositiveSmallIntegerField(default=0)),
                ('seconds_between', models.FloatField(default=5.0)),
                ('media_class', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistFileAssoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.File')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.Playlist')),
            ],
            options={
                'ordering': ['playlist'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
