# Generated by Django 5.1.1 on 2024-09-15 05:53

import django.db.models.deletion
import maio.models.MaioMapType
import maio.models.MaioType
import maio.models.MaioUser
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('maio', '0001_initial'), ('maio', '0002_alter_thumbnail_content_file'), ('maio', '0003_media_is_public'), ('maio', '0004_filestat')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaioMapType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('maio_map_type', models.CharField(choices=[('null', 'Null/None (NULL)'), ('bool', 'Boolean (Number)'), ('null_bool', 'Null Boolean (Number/None)'), ('int', 'Integer (Number)'), ('big_int', 'Big Integer (Number)'), ('small_int', 'Small Integer (Number)'), ('pos_int', 'Positive Integer (Number)'), ('pos_big_int', 'Positive Big Integer (Number)'), ('pos_small_int', 'Positive Small Integer (Number)'), ('cs_int', 'Comma Separated Integer (String)'), ('float', 'Float (Number)'), ('decimal', 'Decimal (Number)'), ('duration', 'Duration (Number)'), ('auto', 'Auto (Number)'), ('big_auto', 'Big Auto (Number)'), ('small_auto', 'Small Auto (Number)'), ('string', 'String'), ('uuid', 'UUID (String)'), ('date', 'Date (String)'), ('time', 'Time (String)'), ('datetime', 'Date Time (String)'), ('datetime_tz', 'Date Time w/ Time Zone (String)'), ('json', 'JSON (String)'), ('xml', 'XML (String)'), ('markdown', 'Markdown (String)'), ('ipv4', 'IPv4 (String)'), ('ipv6', 'IPv6 (String)'), ('mac_address', 'MAC Address (String)'), ('url', 'URL (String)'), ('email', 'Email Address (String)'), ('password', 'Password (Encrypted String)'), ('text', 'Text'), ('file_path', 'File Path (String)'), ('slug', 'Slug'), ('binary', 'Binary (Number)'), ('hex', 'Hexidecimal (Number)'), ('octal', 'Octal (Number)'), ('regex_pattern', 'Regex Pattern (String)'), ('us_phone_number', 'US Phone Number (String)'), ('intl_phone_number', 'International Phone Number (String)')], max_length=20, unique=True, verbose_name='Maio Map Type')),
            ],
        ),
        migrations.CreateModel(
            name='MaioMimeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('mime_type', models.CharField(max_length=254, unique=True, verbose_name='Mime Type')),
                ('extensions', models.CharField(blank=True, max_length=254, null=True, verbose_name='Extensions')),
            ],
        ),
        migrations.CreateModel(
            name='MaioType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('maio_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], max_length=20, unique=True, verbose_name='Maio Type')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('md5sum', models.CharField(editable=False, max_length=32, unique=True, verbose_name='MD5 Sum')),
                ('original_name', models.CharField(editable=False, max_length=1024, verbose_name='Original Name')),
                ('original_extension', models.CharField(blank=True, editable=False, max_length=8, null=True, verbose_name='Original Extension')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='Size (Bytes)')),
                ('mtime', models.FloatField(default=0.0, editable=False, verbose_name='Unix Timestamp')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Time')),
                ('content_file', models.FileField(max_length=1024, upload_to='', verbose_name='Content File')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('mime_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='maio.maiomimetype')),
            ],
        ),
        migrations.AddField(
            model_name='maiomimetype',
            name='maio_type',
            field=models.ForeignKey(default=maio.models.MaioType.default, on_delete=django.db.models.deletion.DO_NOTHING, to='maio.maiotype'),
        ),
        migrations.CreateModel(
            name='MaioUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaioMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=254, unique=True, verbose_name='Key')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Value')),
                ('allow_null', models.BooleanField(default=False, verbose_name='Allow Null?')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled?')),
                ('ins_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Insert DateTime')),
                ('upd_dttm', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
                ('type', models.ForeignKey(default=maio.models.MaioMapType.default, on_delete=django.db.models.deletion.DO_NOTHING, to='maio.maiomaptype')),
                ('user', models.ForeignKey(default=maio.models.MaioUser.default, on_delete=django.db.models.deletion.CASCADE, to='maio.maiouser')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('log', 'Log'), ('info', 'Info'), ('notice', 'Notice'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical'), ('alert', 'Alert'), ('emergency', 'Emergency'), ('exception', 'Exception')], default='log', max_length=10, verbose_name='Log Level')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('message', models.TextField(verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maio.maiouser')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('extension', models.CharField(blank=True, max_length=8, null=True, verbose_name='Extension')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Width (Pixels)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (Pixels)')),
                ('tn_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thumbnail Width (Pixels)')),
                ('tn_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thumbnail Height (Pixels)')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Length (Milliseconsd)')),
                ('author', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Author')),
                ('url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL')),
                ('source', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Source')),
                ('copyright', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Copyright')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Is Hidden?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
                ('comment_type', models.ForeignKey(default=maio.models.MaioMapType.default, on_delete=django.db.models.deletion.DO_NOTHING, to='maio.maiomaptype')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.file')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='maio.tag')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public?')),
            ],
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.maiouser')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.media')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.maiouser')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.media')),
            ],
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('author', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Author')),
                ('url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('caption_date', models.DateTimeField(blank=True, null=True, verbose_name='Caption Date')),
                ('caption', models.TextField(verbose_name='Caption')),
                ('caption_type', models.ForeignKey(default=maio.models.MaioMapType.default, on_delete=django.db.models.deletion.DO_NOTHING, to='maio.maiomaptype')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.media')),
            ],
        ),
        migrations.CreateModel(
            name='MetaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('md5sum', models.CharField(editable=False, max_length=32, unique=True, verbose_name='MD5 Sum')),
                ('content_file', models.FileField(max_length=1024, upload_to='', verbose_name='Meta File')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.file')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('tn_path', models.CharField(max_length=1024)),
                ('default_order', models.PositiveSmallIntegerField(default=0)),
                ('seconds_between', models.FloatField(default=5.0)),
                ('caption', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('caption_type', models.ForeignKey(default=maio.models.MaioMapType.default, on_delete=django.db.models.deletion.DO_NOTHING, to='maio.maiomaptype')),
                ('media', models.ManyToManyField(to='maio.media')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Rating')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.maiouser')),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('md5sum', models.CharField(editable=False, max_length=32, unique=True, verbose_name='MD5 Sum')),
                ('content_file', models.FileField(max_length=1024, upload_to='E:\\Django\\maio\\filestore\\thumbnails', verbose_name='Content File')),
                ('width', models.PositiveIntegerField(verbose_name='Width')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
                ('size', models.PositiveIntegerField(verbose_name='Size (Bytes)')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.file')),
            ],
        ),
        migrations.CreateModel(
            name='FileStat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('num_images', models.PositiveBigIntegerField(editable=False, verbose_name='Number of Images')),
                ('images_bytes', models.PositiveBigIntegerField(editable=False, verbose_name='Number of Bytes of Images')),
                ('num_audio', models.PositiveBigIntegerField(editable=False, verbose_name='Number of Audio Files')),
                ('audio_bytes', models.PositiveBigIntegerField(editable=False, verbose_name='Number of Bytes of Audio')),
                ('num_videos', models.PositiveBigIntegerField(editable=False, verbose_name='Number of Videos')),
                ('videos_bytes', models.PositiveBigIntegerField(editable=False, verbose_name='Number of Bytes of Video')),
                ('num_documents', models.PositiveBigIntegerField(editable=False, verbose_name='Number of Documents')),
                ('documents_bytes', models.PositiveBigIntegerField(editable=False, verbose_name='Number of Bytes of Documents')),
                ('num_others', models.PositiveBigIntegerField(editable=False, verbose_name='Number of Other Files')),
                ('others_bytes', models.PositiveBigIntegerField(editable=False, verbose_name='Number of Bytes of Other Files')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
    ]
