# Generated by Django 5.1.1 on 2024-09-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0007_usersetting_supress_warning_to_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tn_extension',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Thumbnail Extension'),
        ),
        migrations.AlterField(
            model_name='file',
            name='content_file',
            field=models.FileField(max_length=1024, upload_to='E:\\Django\\maio\\filestore\\uploads', verbose_name='Content File'),
        ),
    ]
