# Generated by Django 5.1.1 on 2024-09-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0008_media_tn_extension_alter_file_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_extension',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Thumbnail Extension'),
        ),
        migrations.AlterField(
            model_name='media',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Length (Seconds)'),
        ),
    ]
