# Generated by Django 5.1.1 on 2024-09-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0009_alter_file_original_extension_alter_media_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail_extension',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Thumbnail Extension'),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_extension',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Original Extension'),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_name',
            field=models.CharField(max_length=1024, verbose_name='Original Name'),
        ),
    ]
