# Generated by Django 5.1.1 on 2024-09-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0010_file_thumbnail_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='extension',
            field=models.CharField(default='jpg', max_length=8, verbose_name='Extension'),
        ),
    ]
