# Generated by Django 5.1.1 on 2024-09-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0011_thumbnail_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='uri',
            field=models.CharField(default='/static/media/', max_length=1024, verbose_name='URI'),
        ),
    ]
