# Generated by Django 5.1.1 on 2024-09-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0012_thumbnail_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='display_thumbnails_only',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='supress_warning_to_delete_media',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='default_dashboard_view',
            field=models.CharField(choices=[('default', 'Default: full card display'), ('simple', 'Simple: thumbnails with a minimal amount of meta data'), ('list', 'List: thumbnails in their own row with useful meta data')], default='default', max_length=20, verbose_name='Default Dashboard View'),
        ),
    ]
