# Generated by Django 5.1.1 on 2024-09-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0013_remove_usersetting_display_thumbnails_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='redirect_to_dashboard_after_setting_save',
            field=models.BooleanField(default=False, verbose_name='Redirect to Dashboard After Setting Save'),
        ),
    ]
