# Generated by Django 5.1.1 on 2024-09-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0014_usersetting_redirect_to_dashboard_after_setting_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='default_dashboard_sort',
            field=models.CharField(choices=[('default', 'Default: full card display'), ('simple', 'Simple: thumbnails with a minimal amount of meta data'), ('list', 'List: thumbnails in their own row with useful meta data')], default='default', max_length=50, verbose_name='Default Dashboard Sort'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='default_dashboard_view',
            field=models.CharField(choices=[('default', 'Default: full card display'), ('simple', 'Simple: thumbnails with a minimal amount of meta data'), ('list', 'List: thumbnails in their own row with useful meta data')], default='default', max_length=50, verbose_name='Default Dashboard View'),
        ),
    ]
