# Generated by Django 5.1.1 on 2024-09-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0016_alter_usersetting_default_dashboard_sort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='default_dashboard_sort',
            field=models.CharField(choices=[('name', 'Name (ascending A-Z)'), ('-name', 'Name (descending Z-A)'), ('extension', 'Extension (ascending A-Z)'), ('-extension', 'Extension (descending Z-A)'), ('date_added', 'Date Added (ascending 0-9)'), ('-date_added', 'Date Added (descending 9-0)'), ('date_modified', 'Date Modified (ascending 0-9)'), ('-date_modified', 'Date Modified (descending 9-0)'), ('width', 'Width (ascending 0-9)'), ('-width', 'Width (descending 9-0)'), ('height', 'Height (ascending 0-9)'), ('-height', 'Height (descending 9-0)'), ('length', 'Length (ascending 0-9)'), ('-length', 'Length (descending 9-0)'), ('author', 'Author (ascending A-Z)'), ('-author', 'Author (descending Z-A)'), ('url', 'URL (ascending A-Z)'), ('-url', 'URL (descending Z-A)'), ('source', 'Source (ascending A-Z)'), ('-source', 'Source (descending Z-A)'), ('copyright', 'Copyright (ascending A-Z)'), ('-copyright', 'Copyright (descending Z-A)')], default='-date_added', max_length=50, verbose_name='Default Dashboard Sort'),
        ),
    ]
