# Generated by Django 5.1.1 on 2024-09-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0017_alter_usersetting_default_dashboard_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='redirect_to_dashboard_after_setting_save',
            field=models.BooleanField(default=False, verbose_name='Redirect to Dashboard After Settings Save'),
        ),
    ]
