# Generated by Django 5.1.1 on 2024-09-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0018_alter_usersetting_redirect_to_dashboard_after_setting_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='content_file',
            field=models.FileField(max_length=1024, upload_to='E:\\Django\\maio\\filestore\\meta', verbose_name='Content File'),
        ),
    ]
