# Generated by Django 5.1.1 on 2024-09-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0020_category_media_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caption',
            options={'get_latest_by': ['media', '-caption_date'], 'ordering': ['-caption_date'], 'verbose_name': 'Caption', 'verbose_name_plural': 'Captions'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='filestat',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'File Stat', 'verbose_name_plural': 'File Stats'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.AlterModelOptions(
            name='love',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'Love', 'verbose_name_plural': 'Loves'},
        ),
        migrations.AlterModelOptions(
            name='maiomap',
            options={'get_latest_by': ['-upd_dttm'], 'ordering': ['-upd_dttm'], 'verbose_name': 'Maio User', 'verbose_name_plural': 'Maio Users'},
        ),
        migrations.AlterModelOptions(
            name='maiomaptype',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['maio_map_type'], 'verbose_name': 'Maio Map Type', 'verbose_name_plural': 'Maio Map Types'},
        ),
        migrations.AlterModelOptions(
            name='maiomimetype',
            options={'verbose_name': 'Maio Mime Type', 'verbose_name_plural': 'Maio Mime Types'},
        ),
        migrations.AlterModelOptions(
            name='maiotype',
            options={'ordering': ['maio_type'], 'verbose_name': 'Maio Type', 'verbose_name_plural': 'Maio Types'},
        ),
        migrations.AlterModelOptions(
            name='maiouser',
            options={'verbose_name': 'Maio User', 'verbose_name_plural': 'Maio Users'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'get_latest_by': ['file', '-date_modified'], 'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='metafile',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'MetaFile', 'verbose_name_plural': 'MetaFiles'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlists'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'Thumbnail', 'verbose_name_plural': 'Thumbnails'},
        ),
        migrations.AlterModelOptions(
            name='usersetting',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'User Setting', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.AlterModelTableComment(
            name='caption',
            table_comment='Captions are attached to Media.',
        ),
        migrations.AlterModelTableComment(
            name='category',
            table_comment='Categories are ways to group Media.',
        ),
        migrations.AlterModelTableComment(
            name='file',
            table_comment='Files are saved to the hard drive, network, or cloud.',
        ),
        migrations.AlterModelTableComment(
            name='filestat',
            table_comment='Contains the number of files and their sizes of the current file store.',
        ),
        migrations.AlterModelTableComment(
            name='like',
            table_comment='Contains the Likes for Media.',
        ),
        migrations.AlterModelTableComment(
            name='log',
            table_comment='Logs contain logging information, errors, warnings, etc.',
        ),
        migrations.AlterModelTableComment(
            name='love',
            table_comment='Contains the Loves for Media.',
        ),
        migrations.AlterModelTableComment(
            name='maiomap',
            table_comment='Maio users are also Django users.',
        ),
        migrations.AlterModelTableComment(
            name='maiomaptype',
            table_comment='General Maio Map Types.',
        ),
        migrations.AlterModelTableComment(
            name='maiomimetype',
            table_comment='General Maio Mime Types.',
        ),
        migrations.AlterModelTableComment(
            name='maiotype',
            table_comment='General Maio Types.',
        ),
        migrations.AlterModelTableComment(
            name='maiouser',
            table_comment='Maio users are also Django users.',
        ),
        migrations.AlterModelTableComment(
            name='media',
            table_comment='More than one Media may map onto one File.',
        ),
        migrations.AlterModelTableComment(
            name='metafile',
            table_comment='MetaFiles are saved to the hard drive, network, or cloud.',
        ),
        migrations.AlterModelTableComment(
            name='playlist',
            table_comment='Contains the Playlists for Media.',
        ),
        migrations.AlterModelTableComment(
            name='rating',
            table_comment='Contains the Playlists for Media.',
        ),
        migrations.AlterModelTableComment(
            name='tag',
            table_comment='Contains the Tags for Media.',
        ),
        migrations.AlterModelTableComment(
            name='thumbnail',
            table_comment='Thumbnails are saved to the hard drive, network, or cloud.',
        ),
        migrations.AlterModelTableComment(
            name='usersetting',
            table_comment='User system-wide settings.',
        ),
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default?'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['sort', 'name', 'is_default', 'date_added', '-date_modified'], name='maio_catego_sort_b075c6_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['original_name', 'size', 'mtime', '-modified_time', 'date_added', '-date_modified'], name='maio_file_origina_8b97fe_idx'),
        ),
        migrations.AddIndex(
            model_name='metafile',
            index=models.Index(fields=['content_file', 'date_added', '-date_modified'], name='maio_metafi_content_4329dc_idx'),
        ),
        migrations.AddIndex(
            model_name='thumbnail',
            index=models.Index(fields=['date_added', '-date_modified'], name='maio_thumbn_date_ad_7375f4_idx'),
        ),
    ]
