# Generated by Django 5.1.1 on 2024-09-20 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0021_alter_caption_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='slideshow_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Slideshow Chosen Index'),
        ),
        migrations.AddField(
            model_name='media',
            name='slideshow_tn_uri',
            field=models.URLField(blank=True, null=True, verbose_name='Slideshow Thumbnail URI'),
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('indexes', models.JSONField(verbose_name='Slideshow Indexes (list[float])')),
                ('num_slices', models.PositiveSmallIntegerField(verbose_name='Number of Slices for Indexes')),
                ('length', models.DecimalField(decimal_places=8, max_digits=17, verbose_name='Length (seconds)')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maio.file')),
            ],
            options={
                'verbose_name': 'Slideshow',
                'verbose_name_plural': 'Slideshows',
                'db_table_comment': 'Slideshow meta data for Files.',
                'ordering': ['-date_modified'],
                'get_latest_by': ['-date_modified'],
            },
        ),
    ]
