# Generated by Django 5.1.1 on 2024-09-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0022_media_slideshow_index_media_slideshow_tn_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='length',
            field=models.DecimalField(decimal_places=15, max_digits=22, verbose_name='Length (seconds)'),
        ),
    ]
