# Generated by Django 5.1.1 on 2024-09-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0023_alter_slideshow_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='auto_upload_media',
            field=models.BooleanField(default=False, verbose_name='Auto Upload Media'),
        ),
    ]
