# Generated by Django 5.1.1 on 2024-09-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0024_usersetting_auto_upload_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='default_upload_media_view',
            field=models.CharField(choices=[('default', 'Default: full preview display'), ('simple', 'Simple: thumbnails with a minimal amount of meta data'), ('list', 'List: thumbnails in their own row with useful meta data'), ('thumbnails', 'Thumbnails: display only thumbnails')], default='default', max_length=50, verbose_name='Default Dashboard View'),
        ),
    ]
