# Generated by Django 5.1.1 on 2024-09-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0025_usersetting_default_upload_media_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='maio_theme',
            field=models.CharField(choices=[('default', 'Default: standard Maio theme')], default='default', max_length=50, verbose_name='Maio Theme'),
        ),
    ]
