# Generated by Django 5.1.1 on 2024-09-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0027_alter_usersetting_default_upload_media_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetting',
            old_name='redirect_to_dashboard_after_setting_save',
            new_name='redirect_to_previous_page_after_setting_save',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='previous_page',
            field=models.CharField(default='/', editable=False, max_length=1024, verbose_name='Previous Page'),
        ),
    ]
