# Generated by Django 5.1.1 on 2024-09-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0028_rename_redirect_to_dashboard_after_setting_save_usersetting_redirect_to_previous_page_after_setting_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='maio.tag'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='previous_page',
            field=models.CharField(default='/', max_length=1024, verbose_name='Previous Page'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='redirect_to_previous_page_after_setting_save',
            field=models.BooleanField(default=False, verbose_name='Redirect to Previous Page After Settings Save'),
        ),
    ]
