# Generated by Django 5.1.1 on 2024-09-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0029_alter_media_tags_alter_usersetting_previous_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(to='maio.tag'),
        ),
    ]
