# Generated by Django 5.1.1 on 2024-09-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0030_alter_media_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='display_debug',
            field=models.BooleanField(default=False, verbose_name='Display Debug'),
        ),
    ]
