# Generated by Django 5.1.1 on 2024-09-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0032_libraryshare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryshare',
            options={'get_latest_by': ['-date_modified'], 'ordering': ['-date_modified'], 'verbose_name': 'Library Share', 'verbose_name_plural': 'Library Shares'},
        ),
        migrations.AlterModelTableComment(
            name='libraryshare',
            table_comment='Library sharing between two Maio Users.',
        ),
    ]
