# Generated by Django 5.0.9 on 2024-09-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0034_alter_maiomap_options_alter_maiomap_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Modified'),
        ),
    ]
