# Generated by Django 5.0.9 on 2024-10-19 11:42

import maio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0036_alter_metafile_content_file_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='default_dashboard_per_page',
            field=models.PositiveSmallIntegerField(default=28, validators=[maio.validators.validate_per_page], verbose_name='Default Dashboard Number of Media Per Page'),
        ),
    ]
