# Generated by Django 5.0.9 on 2024-10-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0037_usersetting_default_dashboard_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_converted',
            field=models.BooleanField(default=False, verbose_name='Is Converted?'),
        ),
    ]
