# Generated by Django 5.0.9 on 2024-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0038_file_is_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestat',
            name='audio_converted_bytes',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Number of Bytes of Converted Audio Files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filestat',
            name='num_audio_converted',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Number of Converted Audio Files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filestat',
            name='num_videos_converted',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Number of Converted Videos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filestat',
            name='videos_converted_bytes',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Number of Bytes of Converted Videos'),
            preserve_default=False,
        ),
    ]
