# Generated by Django 5.0.9 on 2024-10-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0039_filestat_audio_converted_bytes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='love',
            name='user',
        ),
    ]
