# Generated by Django 5.0.9 on 2024-10-19 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maio', '0040_remove_love_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='love',
            name='user',
            field=models.ForeignKey(default='46434b91-3aea-4de2-afac-92fba01c8ffd', on_delete=django.db.models.deletion.CASCADE, to='maio.maiouser'),
            preserve_default=False,
        ),
    ]
