"""
Django settings for Maio project.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from __future__ import annotations
from typing import Any

import os
import re
from pathlib import Path

from conf import site_settings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'maio.apps.MaioAppConfig',
    'maioadmin.apps.MaioAdminAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.admindocs.middleware.XViewMiddleware',
    # Maio Middleware
    'maio.middleware.FileStatMiddleware',
    'maio.middleware.UserSettingMiddleware',
]

ROOT_URLCONF = 'maio.urls'

TEMPLATES: list[dict[str, Any]] = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'maio.wsgi.application'

LOGGING: dict[str, Any] = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'maio': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'maio.log'),
        },
        'maio.DEBUG': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'maio.DEBUG.log'),
        },
    },
    'loggers': {
        'maio': {
            'handlers': ['maio'],
            'level': 'DEBUG',
            'proagate': False,
        },
        'maio.DEBUG': {
            'handlers': ['maio.DEBUG'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = True

LOGIN_URL = '/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'filestore')

MEDIA_URL = 'uploads/'

MAIO_STATIC_ROOT = os.path.join(BASE_DIR, 'maio', 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FIXTURE_DIRS = [
    os.path.join(BASE_DIR, '.fixtures'),
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 4294967296 # 4 GB

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1010

DATA_UPLOAD_MAX_NUMBER_FILES = 1000

# Maio specific settings
MAIO_SETTINGS: dict[str, dict[str, Any]] = {
    'filestore': {
        'directory': MEDIA_ROOT,
    },
    'media': {
        'directory': os.path.join(MEDIA_ROOT, 'media'),
        'static_uri': f'/{STATIC_URL}media/',
    },
    'upload': {
        'directory': os.path.join(MEDIA_ROOT, 'uploads'),
    },
    'meta': {
        'directory': os.path.join(MEDIA_ROOT, 'meta'),
    },
    'thumbnail': {
        'directory': os.path.join(MEDIA_ROOT, 'thumbnails'),
        'static_uri': f'/{STATIC_URL}thumbnails/',
    },
    'slideshow': {
        'directory': os.path.join(MEDIA_ROOT, 'slideshows'),
        'static_uri': f'/{STATIC_URL}slideshows/',
    },
    'ffmpeg': {
        'ffmpeg_exe': 'ffmpeg',
        'ffprobe_exe': 'ffprobe',
        'ffplay_exe': 'ffplay',
    },
    'maio_types': {
        'image': {
            'media_directory': os.path.join(MEDIA_ROOT, 'media', 'images'),
            'thumbnail_directory': os.path.join(MEDIA_ROOT, 'thumbnails', 'images'),
            'min_width': 200,
            'min_height': 200,
            'min_inclusive': 'OR',
        },
        'audio': {
            'media_directory': os.path.join(MEDIA_ROOT, 'media', 'audio'),
            'thumbnail_directory': os.path.join(MEDIA_ROOT, 'thumbnails', 'audio'),
            'thumbnail_path': os.path.join(MAIO_STATIC_ROOT, 'maio', 'imgs', 'tn_audio.png'),
        },
        'video': {
            'media_directory': os.path.join(MEDIA_ROOT, 'media', 'videos'),
            'thumbnail_directory': os.path.join(MEDIA_ROOT, 'thumbnails', 'videos'),
        },
        'document': {
            'media_directory': os.path.join(MEDIA_ROOT, 'media', 'documents'),
            'thumbnail_directory': os.path.join(MEDIA_ROOT, 'thumbnails', 'documents'),
            'thumbnail_path': os.path.join(MAIO_STATIC_ROOT, 'maio', 'imgs', 'tn_doc.png'),
            # NOTE: When adding document types, be sure to refactor code in
            #       `conf.MaioConf` and `maio.models.File`
            'pdf': {
                'extensions': ['pdf'],
                'mime_types': ['application/pdf'],
                'thumbnail_path': os.path.join(MAIO_STATIC_ROOT, 'maio', 'imgs', 'tn_pdf.png'),
            },
            'msword': {
                'extensions': [
                    'doc', 'docx', 'docm',
                    'dot', 'dotx', 'dotm',
                    'wbk', 'wpd', 'wp5',
                ],
                'mime_types': [
                    'application/msword',
                    'application/vnd.kde.kword',
                    'application/vnd.lotus-wordpro',
                    'application/vnd.ms-word.document.macroenabled.12',
                    'application/vnd.ms-word.template.macroenabled.12',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document.glossary+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.template.main+xml',
                    'application/vnd.wordperfect',
                    'application/wordperfect5.1',
                    'application/x-abiword',
                ],
                'thumbnail_path': os.path.join(MAIO_STATIC_ROOT, 'maio', 'imgs', 'tn_msdoc.png'),
            },
            'msexcel': {
                'extensions': [
                    'xla', 'xlam',
                    'xll', 'xlm',
                    'xls', 'xlsx', 'xlsm',
                    'xlt', 'xltx', 'xltm',
                    'xlsb',
                ],
                'mime_types': [
                    'application/vnd.ms-excel',
                    'application/vnd.ms-excel.addin.macroenabled.12',
                    'application/vnd.ms-excel.sheet.binary.macroenabled.12',
                    'application/vnd.ms-excel.sheet.macroenabled.12',
                    'application/vnd.ms-excel.template.macroenabled.12',
                    'application/msexcel',
                    'application/x-msexcel',
                    'application/x-ms-excel',
                    'application/x-excel',
                    'application/x-dos_ms_excel',
                    'application/xls',
                    'application/x-xls',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
                ],
                'thumbnail_path': os.path.join(MAIO_STATIC_ROOT, 'maio', 'imgs', 'tn_msexcel.png'),
            },
            'mspowerpoint': {
                'extensions': [
                    'pot', 'potx', 'potm',
                    'pps', 'ppsx', 'ppsm',
                    'ppt', 'pptx', 'pptm',
                    'ppa', 'ppam',
                ],
                'mime_types': [
                    'application/vnd.ms-powerpoint',
                    'application/vnd.ms-powerpoint.addin.macroenabled.12',
                    'application/vnd.ms-powerpoint.presentation.macroenabled.12',
                    'application/vnd.ms-powerpoint.template.macroenabled.12',
                    'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
                    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                    'application/vnd.openxmlformats-officedocument.presentationml.template',
                    'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
                ],
                'thumbnail_path': os.path.join(MAIO_STATIC_ROOT, 'maio', 'imgs', 'tn_doc.png'),
            },
            'msaccess': {
                'extensions': [
                    'mdb',
                ],
                'mime_types': [
                    'application/vnd.ms-access',
                ],
                'thumbnail_path': os.path.join(MAIO_STATIC_ROOT, 'maio', 'imgs', 'tn_doc.png'),
            },
            'xml': {
                'extensions': [
                    'xml',
                ],
                'mime_types': [
                    'text/xml',
                    'text/xml-external-parsed-entity',
                    'application/xml',
                    'application/xml-dtd',
                    'application/xml-external-parsed-entity',
                    'application/xml-patch+xml',
                    'application/3gpdash-qoe-report+xml',
                    'application/3gpp-ims+xml',
                    'application/atom+xml',
                    'application/atomcat+xml',
                    'application/atomdeleted+xml',
                    'application/atomsvc+xml',
                    'application/atxml',
                    'application/auth-policy+xml',
                    'application/beep+xml',
                    'application/calendar+xml',
                    'application/ccmp+xml',
                    'application/ccxml+xml',
                    'application/cdfx+xml',
                    'application/cea-2018+xml',
                    'application/cellml+xml',
                    'application/cnrp+xml',
                    'application/conference-info+xml',
                    'application/cpl+xml',
                    'application/csta+xml',
                    'application/cstadata+xml',
                    'application/dash+xml',
                    'application/davmount+xml',
                    'application/dialog-info+xml',
                    'application/docbook+xml',
                    'application/dskpp+xml',
                    'application/dssc+xml',
                    'application/emergencycalldata.comment+xml',
                    'application/emergencycalldata.deviceinfo+xml',
                    'application/emergencycalldata.providerinfo+xml',
                    'application/emergencycalldata.serviceinfo+xml',
                    'application/emergencycalldata.subscriberinfo+xml',
                    'application/emma+xml',
                    'application/emotionml+xml',
                    'application/epp+xml',
                    'application/fdt+xml',
                    'application/framework-attributes+xml',
                    'application/gml+xml',
                    'application/gpx+xml',
                    'application/held+xml',
                    'application/ibe-key-request+xml',
                    'application/ibe-pkg-reply+xml',
                    'application/im-iscomposing+xml',
                    'application/inkml+xml',
                    'application/its+xml',
                    'application/kpml-request+xml',
                    'application/kpml-response+xml',
                    'application/lgr+xml',
                    'application/load-control+xml',
                    'application/lost+xml',
                    'application/lostsync+xml',
                    'application/mads+xml',
                    'application/marcxml+xml',
                    'application/mathml+xml',
                    'application/mathml-content+xml',
                    'application/mathml-presentation+xml',
                    'application/mbms-associated-procedure-description+xml',
                    'application/mbms-deregister+xml',
                    'application/mbms-envelope+xml',
                    'application/mbms-msk+xml',
                    'application/mbms-msk-response+xml',
                    'application/mbms-protection-description+xml',
                    'application/mbms-reception-report+xml',
                    'application/mbms-register+xml',
                    'application/mbms-register-response+xml',
                    'application/mbms-schedule+xml',
                    'application/mbms-user-service-description+xml',
                    'application/media_control+xml',
                    'application/media-policy-dataset+xml',
                    'application/mediaservercontrol+xml',
                    'application/metalink+xml',
                    'application/metalink4+xml',
                    'application/mets+xml',
                    'application/mods+xml',
                    'application/mrb-consumer+xml',
                    'application/mrb-publish+xml',
                    'application/msc-ivr+xml',
                    'application/msc-mixer+xml',
                    'application/nlsml+xml',
                    'application/oebps-package+xml',
                    'application/omdoc+xml',
                    'application/p2p-overlay+xml',
                    'application/patch-ops-error+xml',
                    'application/pidf+xml',
                    'application/pidf-diff+xml',
                    'application/pls+xml',
                    'application/poc-settings+xml',
                    'application/problem+xml',
                    'application/provenance+xml',
                    'application/prs.rdf-xml-crypt',
                    'application/prs.xsf+xml',
                    'application/pskc+xml',
                    'application/rdf+xml',
                    'application/reginfo+xml',
                    'application/resource-lists+xml',
                    'application/resource-lists-diff+xml',
                    'application/rfc+xml',
                    'application/rlmi+xml',
                    'application/rls-services+xml',
                    'application/rsd+xml',
                    'application/rss+xml',
                    'application/samlassertion+xml',
                    'application/samlmetadata+xml',
                    'application/sbml+xml',
                    'application/scaip+xml',
                    'application/sep+xml',
                    'application/shf+xml',
                    'application/simple-filter+xml',
                    'application/smil+xml',
                    'application/soap+xml',
                    'application/sparql-results+xml',
                    'application/spirits-event+xml',
                    'application/srgs+xml',
                    'application/sru+xml',
                    'application/ssdl+xml',
                    'application/ssml+xml',
                    'application/tei+xml',
                    'application/thraud+xml',
                    'application/ttml+xml',
                    'application/urc-grpsheet+xml',
                    'application/urc-ressheet+xml',
                    'application/urc-targetdesc+xml',
                    'application/urc-uisocketdesc+xml',
                    'application/vcard+xml',
                    'application/vnd.3gpp.access-transfer-events+xml',
                    'application/vnd.3gpp.bsf+xml',
                    'application/vnd.3gpp.mid-call+xml',
                    'application/vnd.3gpp.sms+xml',
                    'application/vnd.3gpp.srvcc-ext+xml',
                    'application/vnd.3gpp.srvcc-info+xml',
                    'application/vnd.3gpp.state-and-event-info+xml',
                    'application/vnd.3gpp.ussd+xml',
                    'application/vnd.3gpp2.bcmcsinfo+xml',
                    'application/vnd.3gpp-prose+xml',
                    'application/vnd.3gpp-prose-pc3ch+xml',
                    'application/vnd.adobe.xdp+xml',
                    'application/vnd.amundsen.maze+xml',
                    'application/vnd.apple.installer+xml',
                    'application/vnd.avistar+xml',
                    'application/vnd.balsamiq.bmml+xml',
                    'application/vnd.biopax.rdf+xml',
                    'application/vnd.chemdraw+xml',
                    'application/vnd.citationstyles.style+xml',
                    'application/vnd.criticaltools.wbs+xml',
                    'application/vnd.ctct.ws+xml',
                    'application/vnd.cyan.dean.root+xml',
                    'application/vnd.dece.ttml+xml',
                    'application/vnd.dm.delegation+xml',
                    'application/vnd.dvb.notif-aggregate-root+xml',
                    'application/vnd.dvb.notif-container+xml',
                    'application/vnd.dvb.notif-generic+xml',
                    'application/vnd.dvb.notif-ia-msglist+xml',
                    'application/vnd.dvb.notif-ia-registration-request+xml',
                    'application/vnd.dvb.notif-ia-registration-response+xml',
                    'application/vnd.dvb.notif-init+xml',
                    'application/vnd.emclient.accessrequest+xml',
                    'application/vnd.eprints.data+xml',
                    'application/vnd.eszigno3+xml',
                    'application/vnd.etsi.aoc+xml',
                    'application/vnd.etsi.cug+xml',
                    'application/vnd.etsi.iptvcommand+xml',
                    'application/vnd.etsi.iptvdiscovery+xml',
                    'application/vnd.etsi.iptvprofile+xml',
                    'application/vnd.etsi.iptvsad-bc+xml',
                    'application/vnd.etsi.iptvsad-cod+xml',
                    'application/vnd.etsi.iptvsad-npvr+xml',
                    'application/vnd.etsi.iptvservice+xml',
                    'application/vnd.etsi.iptvsync+xml',
                    'application/vnd.etsi.iptvueprofile+xml',
                    'application/vnd.etsi.mcid+xml',
                    'application/vnd.etsi.overload-control-policy-dataset+xml',
                    'application/vnd.etsi.pstn+xml',
                    'application/vnd.etsi.sci+xml',
                    'application/vnd.etsi.simservs+xml',
                    'application/vnd.etsi.tsl+xml',
                    'application/vnd.geocube+xml',
                    'application/vnd.google-earth.kml+xml',
                    'application/vnd.gov.sk.e-form+xml',
                    'application/vnd.gov.sk.xmldatacontainer+xml',
                    'application/vnd.hal+xml',
                    'application/vnd.handheld-entertainment+xml',
                    'application/vnd.informedcontrol.rms+xml',
                    'application/vnd.infotech.project+xml',
                    'application/vnd.iptc.g2.catalogitem+xml',
                    'application/vnd.iptc.g2.conceptitem+xml',
                    'application/vnd.iptc.g2.knowledgeitem+xml',
                    'application/vnd.iptc.g2.newsitem+xml',
                    'application/vnd.iptc.g2.newsmessage+xml',
                    'application/vnd.iptc.g2.packageitem+xml',
                    'application/vnd.iptc.g2.planningitem+xml',
                    'application/vnd.irepository.package+xml',
                    'application/vnd.las.las+xml',
                    'application/vnd.liberty-request+xml',
                    'application/vnd.llamagraphics.life-balance.exchange+xml',
                    'application/vnd.marlin.drm.actiontoken+xml',
                    'application/vnd.marlin.drm.conftoken+xml',
                    'application/vnd.marlin.drm.license+xml',
                    'application/vnd.mozilla.xul+xml',
                    'application/vnd.ms-office.activex+xml',
                    'application/vnd.ms-playready.initiator+xml',
                    'application/vnd.ms-printdevicecapabilities+xml',
                    'application/vnd.ms-printing.printticket+xml',
                    'application/vnd.ms-printschematicket+xml',
                    'application/vnd.nokia.conml+wbxml',
                    'application/vnd.nokia.conml+xml',
                    'application/vnd.nokia.iptv.config+xml',
                    'application/vnd.nokia.landmark+wbxml',
                    'application/vnd.nokia.landmark+xml',
                    'application/vnd.nokia.landmarkcollection+xml',
                    'application/vnd.nokia.n-gage.ac+xml',
                    'application/vnd.nokia.pcd+wbxml',
                    'application/vnd.nokia.pcd+xml',
                    'application/vnd.oipf.contentaccessdownload+xml',
                    'application/vnd.oipf.contentaccessstreaming+xml',
                    'application/vnd.oipf.dae.svg+xml',
                    'application/vnd.oipf.dae.xhtml+xml',
                    'application/vnd.oipf.mippvcontrolmessage+xml',
                    'application/vnd.oipf.spdiscovery+xml',
                    'application/vnd.oipf.spdlist+xml',
                    'application/vnd.oipf.ueprofile+xml',
                    'application/vnd.oipf.userprofile+xml',
                    'application/vnd.oma.bcast.associated-procedure-parameter+xml',
                    'application/vnd.oma.bcast.drm-trigger+xml',
                    'application/vnd.oma.bcast.imd+xml',
                    'application/vnd.oma.bcast.notification+xml',
                    'application/vnd.oma.bcast.sgdd+xml',
                    'application/vnd.oma.bcast.smartcard-trigger+xml',
                    'application/vnd.oma.bcast.sprov+xml',
                    'application/vnd.oma.cab-address-book+xml',
                    'application/vnd.oma.cab-feature-handler+xml',
                    'application/vnd.oma.cab-pcc+xml',
                    'application/vnd.oma.cab-subs-invite+xml',
                    'application/vnd.oma.cab-user-prefs+xml',
                    'application/vnd.oma.dd2+xml',
                    'application/vnd.oma.drm.risd+xml',
                    'application/vnd.oma.group-usage-list+xml',
                    'application/vnd.oma.pal+xml',
                    'application/vnd.oma.poc.detailed-progress-report+xml',
                    'application/vnd.oma.poc.final-report+xml',
                    'application/vnd.oma.poc.groups+xml',
                    'application/vnd.oma.poc.invocation-descriptor+xml',
                    'application/vnd.oma.poc.optimized-progress-report+xml',
                    'application/vnd.oma.scidm.messages+xml',
                    'application/vnd.oma.xcap-directory+xml',
                    'application/vnd.omads-email+xml',
                    'application/vnd.omads-file+xml',
                    'application/vnd.omads-folder+xml',
                    'application/vnd.openblox.game+xml',
                    'application/vnd.openxmlformats-officedocument.custom-properties+xml',
                    'application/vnd.openxmlformats-officedocument.customxmlproperties+xml',
                    'application/vnd.openxmlformats-officedocument.drawing+xml',
                    'application/vnd.openxmlformats-officedocument.drawingml.chart+xml',
                    'application/vnd.openxmlformats-officedocument.drawingml.chartshapes+xml',
                    'application/vnd.openxmlformats-officedocument.drawingml.diagramcolors+xml',
                    'application/vnd.openxmlformats-officedocument.drawingml.diagramdata+xml',
                    'application/vnd.openxmlformats-officedocument.drawingml.diagramlayout+xml',
                    'application/vnd.openxmlformats-officedocument.drawingml.diagramstyle+xml',
                    'application/vnd.openxmlformats-officedocument.extended-properties+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.commentauthors+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.comments+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.handoutmaster+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.notesmaster+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.notesslide+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                    'application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.presprops+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.slide',
                    'application/vnd.openxmlformats-officedocument.presentationml.slide+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.slidelayout+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.slidemaster+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
                    'application/vnd.openxmlformats-officedocument.presentationml.slideshow.main+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.slideupdateinfo+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.tablestyles+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.tags+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.template',
                    'application/vnd.openxmlformats-officedocument.presentationml.template.main+xml',
                    'application/vnd.openxmlformats-officedocument.presentationml.viewprops+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.calcchain+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.chartsheet+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.connections+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.dialogsheet+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.externallink+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.pivotcachedefinition+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.pivotcacherecords+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.pivottable+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.querytable+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.revisionheaders+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.revisionlog+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sharedstrings+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheetmetadata+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.table+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.tablesinglecells+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.template.main+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.usernames+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.volatiledependencies+xml',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml',
                    'application/vnd.openxmlformats-officedocument.theme+xml',
                    'application/vnd.openxmlformats-officedocument.themeoverride+xml',
                    'application/vnd.openxmlformats-officedocument.vmldrawing',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document.glossary+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.fonttable+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.template.main+xml',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.websettings+xml',
                    'application/vnd.openxmlformats-package.core-properties+xml',
                    'application/vnd.openxmlformats-package.digital-signature-xmlsignature+xml',
                    'application/vnd.openxmlformats-package.relationships+xml',
                    'application/vnd.otps.ct-kip+xml',
                    'application/vnd.paos.xml',
                    'application/vnd.poc.group-advertisement+xml',
                    'application/vnd.pwg-xhtml-print+xml',
                    'application/vnd.radisys.moml+xml',
                    'application/vnd.radisys.msml+xml',
                    'application/vnd.radisys.msml-audit+xml',
                    'application/vnd.radisys.msml-audit-conf+xml',
                    'application/vnd.radisys.msml-audit-conn+xml',
                    'application/vnd.radisys.msml-audit-dialog+xml',
                    'application/vnd.radisys.msml-audit-stream+xml',
                    'application/vnd.radisys.msml-conf+xml',
                    'application/vnd.radisys.msml-dialog+xml',
                    'application/vnd.radisys.msml-dialog-base+xml',
                    'application/vnd.radisys.msml-dialog-fax-detect+xml',
                    'application/vnd.radisys.msml-dialog-fax-sendrecv+xml',
                    'application/vnd.radisys.msml-dialog-group+xml',
                    'application/vnd.radisys.msml-dialog-speech+xml',
                    'application/vnd.radisys.msml-dialog-transform+xml',
                    'application/vnd.recordare.musicxml',
                    'application/vnd.recordare.musicxml+xml',
                    'application/vnd.route66.link66+xml',
                    'application/vnd.software602.filler.form+xml',
                    'application/vnd.software602.filler.form-xml-zip',
                    'application/vnd.solent.sdkm+xml',
                    'application/vnd.sun.wadl+xml',
                    'application/vnd.sun.xml.calc',
                    'application/vnd.sun.xml.calc.template',
                    'application/vnd.sun.xml.draw',
                    'application/vnd.sun.xml.draw.template',
                    'application/vnd.sun.xml.impress',
                    'application/vnd.sun.xml.impress.template',
                    'application/vnd.sun.xml.math',
                    'application/vnd.sun.xml.writer',
                    'application/vnd.sun.xml.writer.global',
                    'application/vnd.sun.xml.writer.template',
                    'application/vnd.syncml.dm+wbxml',
                    'application/vnd.syncml.dm+xml',
                    'application/vnd.syncml.dmddf+wbxml',
                    'application/vnd.syncml.dmddf+xml',
                    'application/vnd.syncml.dmtnds+wbxml',
                    'application/vnd.syncml.dmtnds+xml',
                    'application/vnd.syncml+xml',
                    'application/vnd.tmd.mediaflex.api+xml',
                    'application/vnd.uoml+xml',
                    'application/vnd.uplanet.alert-wbxml',
                    'application/vnd.uplanet.bearer-choice-wbxml',
                    'application/vnd.uplanet.cacheop-wbxml',
                    'application/vnd.uplanet.channel-wbxml',
                    'application/vnd.uplanet.listcmd-wbxml',
                    'application/vnd.uplanet.list-wbxml',
                    'application/vnd.wap.wbxml',
                    'application/vnd.wv.csp+wbxml',
                    'application/vnd.wv.csp+xml',
                    'application/vnd.wv.ssp+xml',
                    'application/vnd.xmi+xml',
                    'application/vnd.yamaha.openscoreformat.osfpvg+xml',
                    'application/vnd.zzazz.deck+xml',
                    'application/voicexml+xml',
                    'application/watcherinfo+xml',
                    'application/wsdl+xml',
                    'application/wspolicy+xml',
                    'application/xacml+xml',
                    'application/xaml+xml',
                    'application/xcap-att+xml',
                    'application/xcap-caps+xml',
                    'application/xcap-diff+xml',
                    'application/xcap-el+xml',
                    'application/xcap-error+xml',
                    'application/xcap-ns+xml',
                    'application/xcon-conference-info+xml',
                    'application/xcon-conference-info-diff+xml',
                    'application/x-dtbncx+xml',
                    'application/x-dtbook+xml',
                    'application/x-dtbresource+xml',
                    'application/xenc+xml',
                    'application/x-gramps-xml',
                    'application/xhtml+xml',
                    'application/xhtml-voice+xml',
                    'application/xmpp+xml',
                    'application/xop+xml',
                    'application/xproc+xml',
                    'application/xslt+xml',
                    'application/xspf+xml',
                    'application/xv+xml',
                    'application/x-xliff+xml',
                    'application/yin+xml',
                ],
                'thumbnail_path': os.path.join(MAIO_STATIC_ROOT, 'maio', 'imgs', 'tn_xml.png'),
            },
            'text': {
                'extensions': [
                    'txt', 'text', 'log',
                    'cfg', 'ini', 'toml', 'conf',
                    'yml', 'xml', 'json',
                ],
                'mime_types': [
                    'text/plain',
                    'text/1d-interleaved-parityfec',
                    'text/cache-manifest',
                    'text/calendar',
                    'text/css',
                    'text/csv',
                    'text/csv-schema',
                    'text/directory',
                    'text/dns',
                    'text/ecmascript',
                    'text/encaprtp',
                    'text/enriched',
                    'text/example',
                    'text/fwdred',
                    'text/grammar-ref-list',
                    'text/html',
                    'text/javascript',
                    'text/jcr-cnd',
                    'text/markdown',
                    'text/mizar',
                    'text/n3',
                    'text/parameters',
                    'text/parityfec',
                    'text/provenance-notation',
                    'text/prs.fallenstein.rst',
                    'text/prs.lines.tag',
                    'text/prs.prop.logic',
                    'text/raptorfec',
                    'text/red',
                    'text/rfc822-headers',
                    'text/richtext',
                    'text/rtf',
                    'text/rtp-enc-aescm128',
                    'text/rtploopback',
                    'text/rtx',
                    'text/sgml',
                    'text/t140',
                    'text/tab-separated-values',
                    'text/troff',
                    'text/turtle',
                    'text/ulpfec',
                    'text/uri-list',
                    'text/vcard',
                    'text/vnd.a',
                    'text/vnd.abc',
                    'text/vnd.curl',
                    'text/vnd.curl.dcurl',
                    'text/vnd.curl.mcurl',
                    'text/vnd.curl.scurl',
                    'text/vnd.debian.copyright',
                    'text/vnd.dmclientscript',
                    'text/vnd.dvb.subtitle',
                    'text/vnd.esmertec.theme-descriptor',
                    'text/vnd.fly',
                    'text/vnd.fmi.flexstor',
                    'text/vnd.graphviz',
                    'text/vnd.in3d.3dml',
                    'text/vnd.in3d.spot',
                    'text/vnd.iptc.newsml',
                    'text/vnd.iptc.nitf',
                    'text/vnd.latex-z',
                    'text/vnd.motorola.reflex',
                    'text/vnd.ms-mediapackage',
                    'text/vnd.net2phone.commcenter.command',
                    'text/vnd.radisys.msml-basic-layout',
                    'text/vnd.si.uricatalogue',
                    'text/vnd.sun.j2me.app-descriptor',
                    'text/vnd.trolltech.linguist',
                    'text/vnd.wap.si',
                    'text/vnd.wap.sl',
                    'text/vnd.wap.wml',
                    'text/vnd.wap.wmlscript',
                    'text/x-asm',
                    'text/x-c',
                    'text/x-fortran',
                    'text/x-java-source',
                    'text/xml',
                    'text/xml-external-parsed-entity',
                    'text/x-nfo',
                    'text/x-opml',
                    'text/x-pascal',
                    'text/x-setext',
                    'text/x-sfv',
                    'text/x-uuencode',
                    'text/x-vcalendar',
                    'text/x-vcard',
                ],
                'thumbnail_path': os.path.join(MAIO_STATIC_ROOT, 'maio', 'imgs', 'tn_text.png'),
            },
            # /End NOTE
        },
        'other': {
            'media_directory': os.path.join(MEDIA_ROOT, 'media', 'other'),
            'thumbnail_directory': os.path.join(MEDIA_ROOT, 'thumbnails', 'other'),
        },
    },
}

# Maio's site settings loader
# Import conf.site_settings and add references to its attributes.
# THIS WILL OVERRIDE SETTINGS LISTED ABOVE
settings_re = re.compile('[A-Z0-9_]')
for key, value in site_settings.__dict__.items():
    if settings_re.search(key):
        globals().update({key: value})
